# Naam van de workflow
name: Deploy Hugo site to Pages

# Draai deze workflow bij elke push naar de 'main' branch
on:
  push:
    branches:
      - main
  # Hiermee kun je de workflow ook handmatig starten via de Actions-tab in GitHub
  workflow_dispatch:

# Zet permissies voor de GITHUB_TOKEN zodat de deployment kan slagen
permissions:
  contents: read
  pages: write
  id-token: write

# Sta slechts één gelijktijdige deployment toe, annuleer oudere runs
concurrency:
  group: "pages"
  cancel-in-progress: true

# Definieer de taken die uitgevoerd moeten worden
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.124.1/hugo_extended_0.124.1_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Haalt ook je thema op als het een submodule is
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with Hugo
        run: hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4